name: MotD
main: MotD
version: 0.0.4
api-version: 1.16
commands:
   motd:
      description: Set the server MotD
      usage: /<command> [MotD]
      permission: MotD.cmd
permissions:
  MotD.cmd:
    description: Allowed to set and change the MotD
    default: op